# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Hochzeit Babs & Raffi"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Melanie Müller'
author: 'Melanie Müller'
#author_image: "/assets/images/author.jpg"

paginate:	5

url: "/hochzeit-babs-raffi/" # the base hostname & protocol for your site
#baseurl: ""
#used to display twitter cards


#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
